spring:
  application:
    name: data-diff-service
server:
  port: 0
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client:
    serviceUrl:
      #defaultZone: http://registry-service:8761/eureka
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
      #defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true