spring:
  application:
    name: data-diff-service
  data:
    mongodb:
      password: 'waes_assignment'
      uri: mongodb://data_diff_user:${spring.data.mongodb.password}@localhost:27017/data_diff?retryWrites=true&w=majority

server:
  port: 0
  #port: 8384
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: true
    register-with-eureka: true