# Configuring the data-diff-service
spring:
  application:
    name: data-diff-service
  data:
    mongodb:
      password: 'waes_assignment'
      uri: mongodb://data_diff_user:${spring.data.mongodb.password}@localhost:27017/data_diff?retryWrites=true&w=majority

server:
  port: 8083
eureka:
  instance:
    appname: data-diff-service
    instanceId: ${spring.application.name}:${eureka.instance.appname}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

remote:
  decoder-service:
    base-url: http://localhost:8082

#logging:
#  level:
#    ROOT: DEBUG
