# Configuring the decoder-service
spring:
  application:
    name: decoder-service

eureka:
  instance:
    hostname: localhost #hostname used for local tests only, when running with docker-compose this value will be replaced by the the one defined in the env variable
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: false
    register-with-eureka: false