# Configuring the Service Discovery
spring:
  application:
    name: "registry-service"
server:
  port: 8761
eureka:
  instance:
    hostname: data-diff-service
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client: # don't register with yourself because it is not a client
    registerWithEureka: false
    fetchRegistry: false

# Default request logging level
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG