spring:
  application:
    name: "gateway"

# Application port and compression properties
server:
  port: 8080
  # Enable response compression
  compression:
    enabled: true

# Service registry integration properties
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Set default request logging
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    ROOT: DEBUG
