# Configuring the data-diff-service
spring:
  application:
    name: data-diff-service
  data:
    mongodb:
      password: 'waes_assignment'
      uri: mongodb://data_diff_user:${spring.data.mongodb.password}@localhost:27017/data_diff?retryWrites=true&w=majority

server:
  port: 0
eureka:
  instance:
    appname: data-diff-service
    #hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.appname}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false

remote:
  mock:
    port: 9999
  decoder-service:
    base-url: http://localhost:${remote.mock.port}