# Configuring the Service Discovery
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client: # don't register with yourself because it is not a client
    registerWithEureka: false
    fetchRegistry: false