# Configuring the Service Discovery
spring:
  application:
    name: "registry-service"
server:
  port: 8761
eureka:
  instance:
    # Necessary for Docker as it doesn't have DNS entries
    prefer-ip-address: true
    # Necessary for Docker otherwise you will get 172.0.0.x IP
    #ip-address: "${HOST}"
    hostname: eureka
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client: # don't register with yourself because it is not a client
    registerWithEureka: false
    fetchRegistry: false

# Default request logging level
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG